multiplexing.o: multiplexing.c
	echo "compile multiplexing to objec"
	gcc -c 01_multiplexing.c

build: multiplexing.o
	gcc multiplexing.o -o excute

clean:
	echo "clean this resource"
	rm -f *.o excute
